# Array 1: Must refer to a plural (or possibly indefinite) noun. Adjectives and other descriptors are ok.
# Array 2: Predicate. Refer to the subject in array_1 (plural). Ends with punctuation.
# Array 3: mperative for the user. Ends with punctuation
# Array 4: Additional detail to the imperative. Begins with Capital letter, ends with punctuation.
STATEMENT_GENERATOR = [
  [
    'The stars', 
    'The owls', 
    'The crows', 
    'The trees', 
    'The mountains', 
    'The eyes', 
    'Your enemies', 
    'The old', 
    'The young', 
    'The doomed', 
    'The unjust', 
    'The tormented', 
    'The dead', 
    'The clowns',
    'The void between the stars', 
    'The ones spoken of in whispers', 
    'The elder ones beneath the sea',
    'The lizards with painted backs',
    'The elder councillors',
    'The Continuum',
    'The men without eyes',
    'The hierarchies of hell',
    'The choirs of Heaven',
    'The darkest corners of your mind',
    'The faces you see in the darkness',
    'The voices you hear right as you fall asleep',
    'The endless ranks',
    'Those born in starlight',
    'They who pass judgement',
    'The black helicopters above',
    'The silent singers',
    'The hooded figures',
    'The government agents everyone pretends not to see',
    'The servants of Baal',
    'The forgotten gods'
  ],
  [
    'do not know you.', 
    'are not what they seem.', 
    'plot revenge.', 
    'are not lost, but waiting.', 
    'bide their time.', 
    'approach.', 
    'are posessed.', 
    'deepen their eternal hatred.', 
    'yearn for destruction.', 
    'prey upon the unwitting.', 
    'grow nearer.', 
    'grow in unnatural power.', 
    'cannot be stoped.', 
    'are lies meant to distract you from an cruel world.',
    'consume eternally.',
    'see all, see you.',
    'know what you are, and are displeased.',
    'care not for the lives of mortals.',
    'can show you the truth, but require sacrifice.',
    'are more like you than you realize.',
    'will not stop the doom they see for you.',
    'have inflitrated more than you could possibly realize.',
    'have already placed their plans in motion.',
    'will never stop. Never. Stop.',
    'cannot be placated.',
    'accept no quarter, leave nothing but ruin.',
    'rot the ground beneath your feet, even now.',
    'have already passed their verdict.',
    'cannot die, but can awake.',
    'will outlast this world and shall live in the dark nothing.',
    'have taken something from you which you shall not notice until it is too late.',
    'are illegal for you to be aware of.'
  ],
  [
    'Prepare.', 
    'Repent.', 
    'Beware.', 
    'Sleep lightly.', 
    'Don\'t look away.', 
    'Fear them.', 
    'Flee.', 
    'Say your prayers.', 
    'Any last words?', 
    'You cannot win.', 
    'All hope is lost.', 
    'Say your goodbyes.', 
    '*RUN*!',
    'Plead in vain.',
    'Surrender yourself.',
    'Steel your mind against the onslaught.',
    'Hold tight to your sanity.',
    'Rue the day of your birth.',
    'Despair, despair, despair.',
    'Fight valiantly, and fail.',
    'Do you see them, in the corner of your eye?',
    'Defend yourself, while there is still time.',
    'Will you be ready?',
    'Open your eyes.',
    'Forget immediately.',
    'Drink deeply.'
  ],
  [
    'They too, have teeth.', 
    'They lie in wait.', 
    'They come ever faster.', 
    'Your time is coming.', 
    'They haunt the night.', 
    'They are almost upon you.', 
    'They do not show mercy.', 
    'Time is not your friend.', 
    'Winter is coming.', 
    'They are but the first.', 
    'Their voices never cease.', 
    'Blink at your own peril.', 
    'You will not be missed.', 
    'May God have mercy on your soul.',
    'Survival is unlikely.',
    'The world cannot be set right again.',
    'This is predetermined.',
    'They delight in your struggle.',
    'You will never be the same again.',
    'You still have hope, but it is fading.',
    'You witness the setting of the sun, do not assume it will rise again.',
    'You are part of the darkness now.',
    'Greater beings than you have failed this challenge.',
    'We will all be forgotten.',
    'Do not cry to me.',
    'Fear is the only rational part of humanity.',
    'The world is large, we are so small.',
    'There is less time left than you think.',
    'The world ends at their whim.',
    'I pray for you, but still I prepare to grieve.',
    'The path ahead is lonely and inevitable.',
    'Will you be there, when all things fall?',
    'The King is calling.',
    'I see how this ends, and cannot help you.',
    'You are already lost, though you do not realize it yet.'
  ]
]